set(_CATKIN_CURRENT_PACKAGE "uav_mission_planner")
set(uav_mission_planner_VERSION "0.0.0")
set(uav_mission_planner_MAINTAINER "jetson <jetson@todo.todo>")
set(uav_mission_planner_PACKAGE_FORMAT "2")
set(uav_mission_planner_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(uav_mission_planner_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(uav_mission_planner_BUILDTOOL_DEPENDS "catkin")
set(uav_mission_planner_BUILDTOOL_EXPORT_DEPENDS )
set(uav_mission_planner_EXEC_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "mavros_msgs" "nav_msgs" "geometry_msgs")
set(uav_mission_planner_RUN_DEPENDS "roscpp" "rospy" "std_msgs" "sensor_msgs" "mavros_msgs" "nav_msgs" "geometry_msgs")
set(uav_mission_planner_TEST_DEPENDS )
set(uav_mission_planner_DOC_DEPENDS )
set(uav_mission_planner_URL_WEBSITE "")
set(uav_mission_planner_URL_BUGTRACKER "")
set(uav_mission_planner_URL_REPOSITORY "")
set(uav_mission_planner_DEPRECATED "")